name: Upload weekend report

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      METRO_EMAIL: ${{ secrets.METRO_EMAIL }}
      METRO_PASSWORD: ${{ secrets.METRO_PASSWORD }}
      COVID_DASH_LINK: ${{ secrets.COVID_DASH_LINK }}
      SHAREPOINT_URL: ${{ secrets.SHAREPOINT_URL }}
      REPORT_SITE_NAME: ${{ secrets.REPORT_SITE_NAME }}
      REPORT_DOC_LIBRARY: ${{ secrets.REPORT_DOC_LIBRARY }}
      DAILY_REPORT_EXT: ${{ secrets.DAILY_REPORT_EXT }}
      UNION_REPORT_EXT: ${{ secrets.UNION_REPORT_EXT }}
      WEEKEND_REPORT_EXT: ${{ secrets.WEEKEND_REPORT_EXT }}
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set environment variables
      env:
        METRO_EMAIL: ${{ secrets.METRO_EMAIL }}
        METRO_PASSWORD: ${{ secrets.METRO_PASSWORD }}
        COVID_DASH_LINK: ${{ secrets.COVID_DASH_LINK }}
        SHAREPOINT_URL: ${{ secrets.SHAREPOINT_URL }}
        REPORT_SITE_NAME: ${{ secrets.REPORT_SITE_NAME }}
        REPORT_DOC_LIBRARY: ${{ secrets.REPORT_DOC_LIBRARY }}
        DAILY_REPORT_EXT: ${{ secrets.DAILY_REPORT_EXT }}
        UNION_REPORT_EXT: ${{ secrets.UNION_REPORT_EXT }}
        WEEKEND_REPORT_EXT: ${{ secrets.WEEKEND_REPORT_EXT }}
      run: echo "Environment variables set"
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install Dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Script
      run: |
        source .venv/bin/activate
        python scripts/upload_weekend_report.py
